### ISSUE TITLE
Sensors not working on HA v2022 2.0?

### ISSUE THREAD

**Issue by backslashV** [dcshoecomp/homeassistant-cox#11]
It appears the sensors are no longer recognized.

![Screenshot 2022-02-10 115351.png](https://user-images.githubusercontent.com/8752221/153486108-94f664a9-1135-4fcc-a497-5ff7cf40f9c7.png)

In the logs:

```
This error originated from a custom integration.

Logger: custom_components.cox_sensor.sensor
Source: custom_components/cox_sensor/sensor.py:128
Integration: cox_sensor (documentation)
First occurred: February 9, 2022, 7:37:32 PM (4 occurrences)
Last logged: February 9, 2022, 7:37:40 PM

list index out of range
```

```
Logger: homeassistant.components.sensor
Source: custom_components/cox_sensor/sensor.py:138
Integration: Sensor (documentation, issues)
First occurred: February 9, 2022, 7:37:33 PM (2 occurrences)
Last logged: February 9, 2022, 7:37:33 PM

Error adding entities for domain sensor with platform cox_sensor
Error while setting up cox_sensor platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 773, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 563, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 536, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/cox_sensor/sensor.py", line 138, in state
    return self._state
AttributeError: 'cox_sensor' object has no attribute '_state'
```

**Comment by dcshoecomp** [comment]
Unfortunately I no longer use this sensor as I no longer have cox so I have nothing to test it against. I did just release a new version which I just replaced the depreciated device_state_attributes property with the new extra_state_attributes.
You can test this new version and hope for the best.

**Comment by dcshoecomp** [comment]
> 

Unfortunately I no longer use this sensor as I no longer have cox so I have nothing to test it against. I did just release a new version which I just replaced the depreciated device_state_attributes property with the new extra_state_attributes.
You can test this new version and hope for the best.

**Comment by backslashV** [comment]
> > 
> 
> Unfortunately I no longer use this sensor as I no longer have cox so I have nothing to test it against. I did just release a new version which I just replaced the depreciated device_state_attributes property with the new extra_state_attributes. You can test this new version and hope for the best.

Thank you. The issue persists with the latest patch.

**Comment by rgroce** [comment]
I too use this custom component and also have a test instance of HA that's still on 2021.12 and it doesn't work there either.  I don't believe this issue is related to 2022.02, but due to some change at Cox that has broken the component.  Looking at the cox site they have redone the data usage page and broken the information out onto tabs for current, daily, monthly etc. so this is likely the end of the line for this custom component.

**Comment by dcshoecomp** [comment]
> I too use this custom component and also have a test instance of HA that's still on 2021.12 and it doesn't work there either. I don't believe this issue is related to 2022.02, but due to some change at Cox that has broken the component. Looking at the cox site they have redone the data usage page and broken the information out onto tabs for current, daily, monthly etc. so this is likely the end of the line for this custom component.

Unless someone wants to connect with me offline so I can use their account to look at the new page. If it's an easy fix I can make the change, if not then someone else will have to pickup where I left off.

**Comment by rgroce** [comment]
> > I too use this custom component and also have a test instance of HA that's still on 2021.12 and it doesn't work there either. I don't believe this issue is related to 2022.02, but due to some change at Cox that has broken the component. Looking at the cox site they have redone the data usage page and broken the information out onto tabs for current, daily, monthly etc. so this is likely the end of the line for this custom component.
> 
> Unless someone wants to connect with me offline so I can use their account to look at the new page. If it's an easy fix I can make the change, if not then someone else will have to pickup where I left off.

Would screenshots of each of the pages work?

**Comment by UTMK039** [comment]
> > I too use this custom component and also have a test instance of HA that's still on 2021.12 and it doesn't work there either. I don't believe this issue is related to 2022.02, but due to some change at Cox that has broken the component. Looking at the cox site they have redone the data usage page and broken the information out onto tabs for current, daily, monthly etc. so this is likely the end of the line for this custom component.
> 
> Unless someone wants to connect with me offline so I can use their account to look at the new page. If it's an easy fix I can make the change, if not then someone else will have to pickup where I left off.

Hey DC, this was like my favorite custom component. I would be willing to connect to try to fix this. Please just let know what you need.

**Comment by dcshoecomp** [comment]
> > > I too use this custom component and also have a test instance of HA that's still on 2021.12 and it doesn't work there either. I don't believe this issue is related to 2022.02, but due to some change at Cox that has broken the component. Looking at the cox site they have redone the data usage page and broken the information out onto tabs for current, daily, monthly etc. so this is likely the end of the line for this custom component.
> > 
> > 
> > Unless someone wants to connect with me offline so I can use their account to look at the new page. If it's an easy fix I can make the change, if not then someone else will have to pickup where I left off.
> 
> Hey DC, this was like my favorite custom component. I would be willing to connect to try to fix this. Please just let know what you need.

Send me an email dcshoecomp@lemaid.com

**Comment by awilliams84** [comment]
Are we dead in the water with this integration? It was one of my favorites too

**Comment by UTMK039** [comment]
> Are we dead in the water with this integration? It was one of my favorites too

Yes, unfortunately it would appear so. I e-mailed DC some files to see if it would be an easy fix, but I never heard back so I'm assuming it wasn't as simple as he originally thought to fix.

**Comment by dcshoecomp** [comment]
> > Are we dead in the water with this integration? It was one of my favorites too
> 
> Yes, unfortunately it would appear so. I e-mailed DC some files to see if it would be an easy fix, but I never heard back so I'm assuming it wasn't as simple as he originally thought to fix.

Hey UTM I actually never got the files. I was wondering what happened to them. I am sending you a new emai.

**Comment by UTMK039** [comment]
> > > Are we dead in the water with this integration? It was one of my favorites too
> > 
> > 
> > Yes, unfortunately it would appear so. I e-mailed DC some files to see if it would be an easy fix, but I never heard back so I'm assuming it wasn't as simple as he originally thought to fix.
> 
> Hey UTM I actually never got the files. I was wondering what happened to them. I am sending you a new emai.

I wondered! I even followed up with another e-mail. ANYWAY, I just re-sent the two .HAR files and .HTML directly to your e-mail. I guess let me know on here if you don't get those and I can upload them Google Drive or something and post the link. Thanks so much for responding!!

**Comment by UTMK039** [comment]
> > > Are we dead in the water with this integration? It was one of my favorites too
> > 
> > 
> > Yes, unfortunately it would appear so. I e-mailed DC some files to see if it would be an easy fix, but I never heard back so I'm assuming it wasn't as simple as he originally thought to fix.
> 
> Hey UTM I actually never got the files. I was wondering what happened to them. I am sending you a new emai.

Hey, did you get the new .har file I sent over on 3/9 as requested?

**Comment by dcshoecomp** [comment]
> 

Yup thanks. It is not looking good though. I might have to switch the way it is rendering the page to execute javascript. It seems they are  obfuscating most of their code behind javascript https://www.cox.com/orgone-Obed-abhorrow-That-Safe-Yong-abroach-it-p like that fun crap.
