### ISSUE TITLE
Errors with sensor in HA 114.2

### ISSUE THREAD

**Issue by tomschlick** [dcshoecomp/homeassistant-cox#7]
Seeing this after installing last night. The modem restart kill switch works fine, however the sensor throws this error related to no state.

```
2020-08-17 13:19:14 ERROR (SyncWorker_5) [custom_components.cox_sensor.sensor] Expecting value: line 2 column 1 (char 2)
2020-08-17 13:19:14 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up cox_sensor platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 187, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 452, in _async_add_entity
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 290, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 314, in _async_write_ha_state
    sstate = self.state
  File "/config/custom_components/cox_sensor/sensor.py", line 121, in state
    return self._state
AttributeError: 'cox_sensor' object has no attribute '_state'
```

**Comment by terryhonn** [comment]
I'm seeing this as well, happy to help troubleshoot if need be.

EDIT: Actually, I just updated this code to latest, restarted HA and the Cox sensors and switch are there, no errors in log.

**Comment by tomschlick** [comment]
Yup just updated yesterday and it started working. Closing this out.

**Comment by backslashV** [comment]
Hi,
I am seeing the same error for the sensors in the latest update.

```
Error adding entities for domain sensor with platform cox_sensor
Error while setting up cox_sensor platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 317, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 319, in _async_write_ha_state
    sstate = self.state
  File "/config/custom_components/cox_sensor/sensor.py", line 138, in state
    return self._state
AttributeError: 'cox_sensor' object has no attribute '_state'
```
Also,

```
Logger: custom_components.cox_sensor.sensor
Source: custom_components/cox_sensor/sensor.py:128
Integration: cox_sensor (documentation)
First occurred: 11:15:45 PM (4 occurrences)
Last logged: 11:15:57 PM

list index out of range
```
